version: '3'

services:

  servidor-ftp:
    image: bogem/ftp
    container_name: servidor-ftp
    environment:
      FTP_PASS: rodrigues
      FTP_USER: rodrigues
      PASV_ADDRESS: 127.0.0.1
    volumes:
      - "/home/vsftpd"
      - "/var/log/vsftpd"
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    restart: always

  mongo-db:
    image: tutum/mongodb
    container_name: mongo-db
    environment:
      AUTH: "no"
    volumes:
        - "/data/db"
    ports:
      - "27017:27017"
      - "28017:28017"

  postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  sonarqube:
    image: bitnami/sonarqube
    container_name: sonarqube
    ports:
      - '9000:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=rodrigues
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=rodrigues
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=rodrigues
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=rodrigues
      - SONARQUBE_DATABASE_NAME=rodrigues
      - SONARQUBE_DATABASE_USER=rodrigues
      - SONARQUBE_DATABASE_PASSWORD=rodrigues
    volumes:
      - "sonarqube_data:/bitnami"

volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local

